### ISSUE TITLE
Collect Roman specific source data

### ISSUE THREAD

**Issue by klokan** [klokantech/roman-empire#1]
The first step is to collect the data displayed in DARE, which has open license and can be placed on GitHub - ideally as GeoJSON in this repository in a "data" folder.

Important for the first version of the vector maps are especially:
provinces, roads, places

A complete list of all layers in DARE is in the Implementation notes from the meeting today:
https://docs.google.com/document/d/1JH2t2NiVf0j3EJHnYKw6t-pPzJDbWaF5cO4Kbi13-RY/edit#

@johaahlf - could you please provide these until next meeting (Wednesday)?

**Comment by johaahlf** [comment]
Hi Petr,
I will take care of this today and upload the GEOJSON files to the data folder.

Best wishes,
Johan

Från: Petr Pridal [mailto:notifications@github.com]
Skickat: den 1 september 2017 18:25
Till: klokantech/roman-empire-vector-map <roman-empire-vector-map@noreply.github.com>
Kopia: Johan Åhlfeldt <johan.ahlfeldt@ctr.lu.se>; Mention <mention@noreply.github.com>
Ämne: [klokantech/roman-empire-vector-map] Collect data (#1)


The first step is to collect the data displayed in DARE, which has open license and can be placed on GitHub - ideally as GeoJSON in this repository in a "data" folder.

Especially these are important for the first version of the vector maps:
provinces, roads, places

A complete list of all layers in DARE is in the Implementation notes from the meeting today:
https://docs.google.com/document/d/1JH2t2NiVf0j3EJHnYKw6t-pPzJDbWaF5cO4Kbi13-RY/edit#<https://docs.google.com/document/d/1JH2t2NiVf0j3EJHnYKw6t-pPzJDbWaF5cO4Kbi13-RY/edit>

@johaahlf<https://github.com/johaahlf> - could you please provide these until next meeting (Wednesday)?

**Comment by klokan** [comment]
Available in the data folder:

https://github.com/klokantech/roman-empire/tree/master/data

Thanks @johaahlf
