### ISSUE TITLE
Not enough padding in the vector tiles?

### ISSUE THREAD

**Issue by idastorm** [klokantech/roman-empire#11]
![image](https://user-images.githubusercontent.com/31061856/32141972-b5372204-bc8d-11e7-8980-582fe3d629b8.png)

Label of major settlement getting cut off. Can be solved by checking the "Avoid Edges" which is "recommended in layers that don't have enough padding in the vector tile to avoid collision..." 

When checked it looks like this:

![image](https://user-images.githubusercontent.com/31061856/32141989-416ae5bc-bc8e-11e7-8d73-c546f747c368.png)

Not many place labels are showing, is this acceptable  @johaahlf ? Is there another way around it @klokan ?

**Comment by klokan** [comment]
I have not seen this issue in Mapbox GL JS viewer for a while...
Please provide an URL to the map view where this is visible (it is best to give links next to the images).

We could increase the buffers for layers with larger labels. This is required if we want to get high-res printing out of the style too.
Technical details for implementation with tippecanoe: https://github.com/mapbox/tippecanoe/issues/385

Still - please concentrate on implementing all the layers in style properly. The avoid edges as a good workaround for now - so you can finish all other tasks on the styling...

**Comment by idastorm** [comment]
In the last couple of updates of the map, there does not seem to be a problem. I have now uploaded a style where "avoid edges" is not checked. I have done multiple changes in the style since posting the issue and do not know what solved it. The screenshots are from the online editor, so the style.json version with this issue was probably never uploaded. If we find this problem upon further scrutiny maybe we can re-open the issue.
