### ISSUE TITLE
General questions on Mapbox GL overlays (markers, GeoJSON, HTML)

### ISSUE THREAD

**Issue by rsimon** [klokantech/roman-empire#12]
Hi all,

just dropping in quickly to say two things:

1. the map is awesome :-)
2. do you have any thoughts and/or interest in collaborating with regard to implementing added functionality on top of the base map? In the medium/long run I'd really like to integrate your map with Peripleo. That would inevitably mean switching out Leaflet with Mapbox GL for us, I guess; and re-implementing basic overlay functionality: point markers, GeoJSON shapes, custom HTML (i.e. a replacement for Leaflet's [DIV icon](http://leafletjs.com/reference-1.2.0.html#divicon). Do you know if that's feasible in Mapbox GL at all?

**Comment by rsimon** [comment]
Another thing (maybe we can talk about this at Linked Pasts III): can (or do?) the vector tiles include multiple labels, with a timestamp attached? So that they can be switched on the fly by the client?

**Comment by klokan** [comment]
Great to see you @klokantech GitHub repo, @rsimon ;-)

1. Thanks for praising!
2. Sure. Check https://www.mapbox.com/mapbox-gl-js/api/. Glad to help - and looking forward to meeting you again - at LPIII. Hope to have some time for hacking together again.
3. There are labels for latin, greek and modern in vector tiles. We will add the language switcher next week under #13
