### ISSUE TITLE
Test of the print out

### ISSUE THREAD

**Issue by klokan** [klokantech/roman-empire#14]
We can use https://github.com/klokantech/thumbnail-gl

The map visible at https://klokantech.github.io/roman-empire/#4.44/43.015/15.874 with style
https://klokantech.github.io/roman-empire/style.json

@petrsloup - could you please try it - and give us a command for that?

**Comment by petrsloup** [comment]
Functionality added to the thumbnail-gl -- you can now pass custom parameters to create additional image apart from the thumbnails.

The precise parameters depend on how big you want to print the map.
Examples (converted to jpegs):

`docker run -v $(pwd):/data klokantech/thumbnail-gl https://klokantech.github.io/roman-empire/style.json "-x 15.874 -y 43.015 -z 3.5 -w 1000 -h 700 -r 8"`
![custom_3 5](https://user-images.githubusercontent.com/707817/32467379-b8c3352a-c34a-11e7-900b-aeff334d123a.jpg)

`docker run -v $(pwd):/data klokantech/thumbnail-gl https://klokantech.github.io/roman-empire/style.json "-x 15.874 -y 43.015 -z 4.5 -w 2000 -h 1400 -r 4"`
![custom_4 5](https://user-images.githubusercontent.com/707817/32467341-9042cad4-c34a-11e7-95d7-b8498e7dfd0c.jpg)

`docker run -v $(pwd):/data klokantech/thumbnail-gl https://klokantech.github.io/roman-empire/style.json "-x 15.874 -y 43.015 -z 5.5 -w 4000 -h 2800 -r 2"`
![custom_5 5](https://user-images.githubusercontent.com/707817/32467353-9dd79814-c34a-11e7-870f-850e948f3b5c.jpg)

`docker run -v $(pwd):/data klokantech/thumbnail-gl https://klokantech.github.io/roman-empire/style.json "-x 15.874 -y 43.015 -z 6.5 -w 8000 -h 5600 -r 1"`
![custom_6 5](https://user-images.githubusercontent.com/707817/32467471-f1475e8a-c34a-11e7-9530-eb3ea7f082b9.jpg)
