### ISSUE TITLE
Zoom Control missing

### ISSUE THREAD

**Issue by johaahlf** [klokantech/roman-empire#17]
#17 After the switch language dropdown was added, the zoom in/out control doesn't appear anymore (Firefox, Chrome). The following line seems to be missing. I can add that myself:
`map.addControl(new mapboxgl.NavigationControl());`
I have implemented something similar on the DARE domain when I was playing around with the Mapbox-gl-js API, https://dare.ht.lu.se/vector/#9/43.7820/5.1240/0/60
I made the Javascript change style, which is a bit slower.
I have just installed the Tilserver-GL on one of my domains using Docker, http://ht-uppakra.ht.lu.se:8080/
This is currently the only server running Ubuntu 16.04 LTS.

**Comment by johaahlf** [comment]
I just discovered that the Uppakra site is still behind our firewall, so its not accessible from outside yet. However the Tileserver-GL is up and running with the Zürich test data.

**Comment by johaahlf** [comment]
I have added the missing code and now the Navigation control is visible again :-)

**Comment by klokan** [comment]
Great! Thanks.

**Comment by klokan** [comment]
BTW For the blog post - I would love to send people to URL:
https://klokantech.github.io/roman-empire/#4.65/45.684/13.714

**Comment by johaahlf** [comment]
Ok, the implementation at DARE is for my own testing purposes and how to implement the full user interface using Mapbox-gl-js in the future instead of OpenLayers. @klokan

**Comment by klokan** [comment]
BTW the OpenLayers can display the same style too - just fine - with
https://github.com/boundlessgeo/ol-mapbox-style
