### ISSUE TITLE
Zoom levels in generate-tiles.sh

### ISSUE THREAD

**Issue by johaahlf** [klokantech/roman-empire#18]
The zoom levels need to be changed in the script generate-tiles.sh to correspond to the raster map at dare.ht.lu.se. In general they need to be one less. Can I do that myself? What does the -B parameter stands for? -Z seems to be min-zoom and -z max-zoom. @klokan

**Comment by klokan** [comment]
Please - do the modification yourself @johaahlf 

The tippecanoe is documented at:
https://github.com/mapbox/tippecanoe#dropping-a-fixed-fraction-of-features-by-zoom-level

**Comment by johaahlf** [comment]
Thanks, that explains things :)
