### ISSUE TITLE
mbtiles file dont compile

### ISSUE THREAD

**Issue by johaahlf** [klokantech/roman-empire#19]
after I added two layers (10m_lakes and 10m_rivers) and changed zoom level settings in the task/generate-tiles.sh the mbtiles doesn't show up on the map. @klokan

**Comment by klokan** [comment]
It seems there is a problem in your last edit:

    ./task/generate-tiles.sh: line 110: /build/10m_lakes.mbtiles: No such file or directory

https://travis-ci.org/klokantech/roman-empire#L685

**Comment by johaahlf** [comment]
I removed the Lakes and Rivers layers and now the mbtiles file compile again. I dont know why it didn't work. @klokan
