### ISSUE TITLE
Add source information in README

### ISSUE THREAD

**Issue by natslaughter** [klokantech/roman-empire#21]
Providing source information showing where map elements such as settlements, forts and especially the road network were derived from would be helpful. 

Great project!

**Comment by johaahlf** [comment]
Hi @natslaughter, source information will be added at the end of the project. At this point, it is just a demo.

**Comment by johaahlf** [comment]
PS. source information is available at the the Digital Atlas of the Roman Empire (DARE), https://dare.ht.lu.se 
This project is a development of DARE with the aim of changing the background tiles from raster to vector tiles. @natslaughter
