### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by johaahlf** [klokantech/roman-empire#22]
The last places update failed to build. I read the log file and its seems it is not related to the geojson files but the system files @klokan

**Comment by johaahlf** [comment]
Maybe the errors were temporary. Yesterday it built again.

**Comment by klokan** [comment]
The build happens now on the free Travis infrastructure - not at klokan side. Travis can timeout or fail on some random occasions for long tasks.

We could move the build into our internal company Continuous Integration system (powered by Jenkins).

It would be more reliable and monitored - but it is a service to keep in mind and maintain in future on our side. The build, reliable hosting on CDN and extra global datasets (such as the contour lines and hill shading) on CDN could be offered as a part of https://tIlehosting.com/.
