### ISSUE TITLE
Github - save with versions

### ISSUE THREAD

**Issue by klokan** [klokantech/roman-empire#7]
Please update the files with correct versioning on GitHub.

This means to "commit" the files into this repository.

You can use `git` on command line or graphical user interface such as: 

https://desktop.github.com/
or
https://www.sourcetreeapp.com/

**Comment by idastorm** [comment]
Test


________________________________
Från: Petr Pridal <notifications@github.com>
Skickat: den 22 september 2017 11:43
Till: klokantech/roman-empire-vector-map
Kopia: idastorm; Assign
Ämne: Re: [klokantech/roman-empire-vector-map] Github - save with versions (#7)


Assigned #7<https://github.com/klokantech/roman-empire-vector-map/issues/7> to @idastorm<https://github.com/idastorm>.
