### ISSUE TITLE
Creating the style in Maputnik

### ISSUE THREAD

**Issue by klokan** [klokantech/roman-empire#8]
The job is to recreate the look&feel of the http://dare.ht.lu.se/ with the vector tiles.

Documentation for Maputnik (the open-source online editor) at: https://github.com/maputnik/editor/wiki

Use the link "Edit the map" in the bottom of GitHub README.md.

Be sure to "Export" in Maputnik and drag&drop the right style.json into this repo.

**Comment by idastorm** [comment]
A first style draft has been completed and it looks pretty good! All the labels of the places are currently in Latin.

**Comment by klokan** [comment]
Great job @idastorm. Thanks!
