### ISSUE TITLE
Mapbox Studio Classic / TileMill2 tests

### ISSUE THREAD

**Issue by klokan** [klokantech/roman-empire#9]
We have made vector tiles with SQLite in and basic style of these with Mapnik CartoCSS.

Thanks @idastorm !

The project files are now at:

https://github.com/klokantech/roman-empire/tree/tilemill2

@idastorm Could you please drop here some screenshots of the style made in Mapbox Studio Classic - for reference?

**Comment by idastorm** [comment]
## **Zoom level 5**
![zoom5](https://user-images.githubusercontent.com/31061856/31881001-754d956a-b7e2-11e7-97f8-2a4900fa1e4e.JPG)

## **Zoom level 6**
![zoom6](https://user-images.githubusercontent.com/31061856/31881021-8022bbb4-b7e2-11e7-9d7c-78d5491dee81.JPG)

## **Zoom level 7**
![zoom7](https://user-images.githubusercontent.com/31061856/31881023-8066de48-b7e2-11e7-8ef7-745151d666cc.JPG)

## **Zoom level 9**
![zoom9](https://user-images.githubusercontent.com/31061856/31881025-808193c8-b7e2-11e7-87df-e3e607814f9f.JPG)

## **Zoom level 11**
![zoom11](https://user-images.githubusercontent.com/31061856/31881026-809ad180-b7e2-11e7-8471-88c116d8a9e3.JPG)

**Comment by klokan** [comment]
Cool! Thanks.
